language: d
sudo: false

d:
    - dmd-2.070.0-b1
    - dmd-2.069.2
    - dmd-2.068.2
    - dmd-2.067.1
    - dmd-2.066.1
    - ldc-0.16.1
    - gdc-5.2.0
    - gdc-4.9.2

addons:
  apt:
    packages:
    - libsqlite3-0
    - libsqlite3-dev
